### ISSUE TITLE
Fast Charge not work.

### ISSUE THREAD

**Issue by Kissycat** [Rohail33/Realking_xiaomi_xaga#2]
The charging current will fall to 3A in mins after plug in cable, caused by commits between [3ddb387](https://github.com/Rohail33/Realking_xiaomi_xaga/commit/3ddb387c9c5c43bac6c01393a8607962b6d3f3b0) and [56c7e0b](https://github.com/Rohail33/Realking_xiaomi_xaga/commit/56c7e0b67f73409ce051a6f1ccffaeed9d404912) on Mar 30, 2023.

Only tested on MIUI 13.0.14 eu..
![image](https://github.com/Rohail33/Realking_xiaomi_xaga/assets/20614068/c1c3705f-7475-40a4-8861-5e81f5b5263f)

**Comment by Rohail33** [comment]
@Kissycat are you sure these commits are the cause? Some of them are upstreaming commits which are also applied in official trees for mtk, and the last one you've mentioned, is some changes in defconfig. Can specify what's the actual cause? Mihw etc? Plus these changes are recently done, i haven't released an update with these changes. 
Anyways, try going to fkm, and setting up thermal profile to PUBg or extreme, should help

**Comment by Kissycat** [comment]
> @Kissycat are you sure these commits are the cause? 

Yes, I am sure, 
I am also confuse about that, but it is. 
There is nothing else important changed power supply etc, also the kernel version bumps. 
However, my fast charge only works after removing the commits on Mar 30, so it must be something strange happened on these commits, maybe one of them.
I had also tried comment MIHW in defconfig, but nothing changed.
Yes, I know it hasn't been released yet, I just compile it for a taste, then I found it is much better than offical kernel, so I keep using, and encountered this problem. 
At last, Thanks for your project, it is pretty good.
( FKM does not work on this issue.. )

**Comment by Rohail33** [comment]
> > @Kissycat are you sure these commits are the cause?
> 
> Yes, I am sure, I am also confuse about that, but it is. There is nothing else important changed power supply etc, also the kernel version bumps. However, my fast charge only works after removing the commits on Mar 30, so it must be something strange happened on these commits, maybe one of them. I had also tried comment MIHW in defconfig, but nothing changed. Yes, I know it hasn't been released yet, I just compile it for a taste, then I found it is much better than offical kernel, so I keep using, and encountered this problem. At last, Thanks for your project, it is pretty good. ( FKM does not work on this issue.. )

Hmm okeh I'll look into this, the issue is we dunno any other method for upstreaming the official one seems to just make the kernel unbootable. But lel I'll look into it

**Comment by Kissycat** [comment]
> make the kernel unbootable. 

Emm, I am not sure, maybe [this](https://github.com/zzh-zzh-zzh/android_gki_kernel_5.10_common/commit/d786b60dfc7fa02df89684ceb06d55f2359de083) could help?

**Comment by Kissycat** [comment]
It is not caused by MIHW, but the other configs in [56c7e0b](https://github.com/Rohail33/Realking_xiaomi_xaga/commit/56c7e0b67f73409ce051a6f1ccffaeed9d404912#diff-adf40ac38f83671752f67ef6c503e41608379d02663490b27a39d449a3ef446aL406) 
Confirmed.
Just remove the HZ setting.
Check from back to front is not a good idea..

**Comment by Rohail33** [comment]
Okeh, I'll be doing some cleanup in my stable branch, so if you find any working upstreaming commits do let me know.

**Comment by Kissycat** [comment]
> working upstreaming commits 

Maybe you can add MGLRU from google android13-5.10 or just his [backport](https://github.com/zzh-zzh-zzh/android_gki_kernel_5.10_common), it is really awsome for xaga.

**Comment by Rohail33** [comment]
Oke thanks, will add it , let's see if works on mtk

**Comment by Kissycat** [comment]
> Oke thanks, will add it , let's see if works on mtk

It works, you can have an experience [here](https://luna.lovegood.cyou/s/4RcK)

**Comment by Rohail33** [comment]
Oke great 👍, will add these today
