### ISSUE TITLE
Will the source work with K50g?

### ISSUE THREAD

**Issue by IamCOD3X** [Rohail33/Realking_xiaomi_xaga#3]
As it support K50i

**Comment by Rohail33** [comment]
> As it support K50i

Well idk about the device k50g , tell me the specs or give a link where i can see about it

**Comment by IamCOD3X** [comment]
Here it is
Full name **K50 Gaming**
Codename:  **Ingres**
https://forum.xda-developers.com/f/xiaomi-poco-f4-gt-redmi-k50-gaming.12699/

**Comment by Rohail33** [comment]
> Here it is Full name **K50 Gaming** Codename: **Ingres** https://forum.xda-developers.com/f/xiaomi-poco-f4-gt-redmi-k50-gaming.12699/

No you can't use this tree for f4 gt , bcz both have different chipsets and Almost everything is different in both devices.

**Comment by IamCOD3X** [comment]
Ok thanks for the informating, I was confused in between K50i and K50g.
Closing the issues.
have a nice day
